STATUS_PUBLISHING = "publishing"
STATUS_PUBLISHED = "published"
STATUS_NOTIFYING_BORING = "notifying_boring"
STATUS_SKIPPED_BORING = "skipped_boring"
STATUS_PUBLISH_FAILED = "publish_failed"
STATUS_BORING_NOTICE_FAILED = "boring_notice_failed"
STATUS_PUBLISH_UNKNOWN = "publish_unknown"
STATUS_BORING_NOTICE_UNKNOWN = "boring_notice_unknown"

IN_PROGRESS_STATUSES = {
    STATUS_PUBLISHING,
    STATUS_NOTIFYING_BORING,
}

FINAL_STATUSES = {
    STATUS_PUBLISHED,
    STATUS_SKIPPED_BORING,
    STATUS_PUBLISH_FAILED,
    STATUS_BORING_NOTICE_FAILED,
    STATUS_PUBLISH_UNKNOWN,
    STATUS_BORING_NOTICE_UNKNOWN,
}

MANUAL_PUBLISHABLE_STATUSES = {
    STATUS_SKIPPED_BORING,
    STATUS_PUBLISH_FAILED,
    STATUS_BORING_NOTICE_FAILED,
}

VISIBLE_IN_STATS = {
    STATUS_PUBLISHED,
}

REASON_WORTHY = "worthy"
REASON_BORING_DAY = "boring_day"
