from __future__ import annotations

import asyncio
import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.ext.asyncio import async_engine_from_config

from app.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def get_url() -> str:
    return os.getenv("DB_URL") or config.get_main_option("sqlalchemy.url")


def _include_object(obj, name, type_, reflected, compare_to) -> bool:
    # The `core` schema (core.person / core.chat) is owned and migrated centrally
    # in core-postgres; the FK-target stubs in app.models must never be created,
    # dropped or autogenerated by quoto.
    if getattr(obj, "schema", None) == "core":
        return False
    return True


# quoto's tables live in the `quoto` schema; keep alembic's version table there
# too and let it see cross-schema objects (for the core FK stubs) without
# managing them.
_SCHEMA_KW = dict(
    version_table_schema="quoto",
    include_schemas=True,
    include_object=_include_object,
)


def run_migrations_offline() -> None:
    context.configure(
        url=get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        **_SCHEMA_KW,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection) -> None:
    # The alembic version table lives in the `quoto` schema
    # (version_table_schema). alembic creates quoto.alembic_version *before*
    # running the migration body, and Table.create() never auto-creates a
    # schema -- so on a fresh database the schema must exist first or the
    # version-table DDL aborts with InvalidSchemaName. Create it up front, but
    # ONLY when it's actually missing: on the shared core-postgres the schema is
    # pre-provisioned by a superuser and the restricted runtime role (quoto_core)
    # has no CREATE on the database, so an unconditional CREATE SCHEMA raises
    # InsufficientPrivilege on every boot. pg_namespace is world-readable.
    has_schema = connection.exec_driver_sql(
        "SELECT 1 FROM pg_namespace WHERE nspname = 'quoto'"
    ).scalar()
    if not has_schema:
        connection.exec_driver_sql("CREATE SCHEMA IF NOT EXISTS quoto")
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        **_SCHEMA_KW,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = get_url()

    connectable = async_engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
